# Generated by Django 3.1.5 on 2021-01-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
