# Generated by Django 3.1.5 on 2021-01-17 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210116_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='lane_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
